### ISSUE TITLE
Error "redirect_uri did not match any configured URIs" when using own client app ID

### ISSUE THREAD

**Issue by sensibleish** [ZeeZide/Shrugs#1]
No help needed, just posting for other users. I tried to add an account to Shrug using the "own Slack App ID" option. After authenticating to Slack, the process ended in an error:

`redirect_uri did not match any configured URIs. Passed URI: x-slack-zeezide://localhost/oauth-redirect`

The solution was to update the configuration of my custom Slack app:

1. Navigate to the custom app's settings on api.slack.com
2. Click `OAuth & Permissions`
3. In the `Redirect URLs` section, click `Add New Redirect URL`
4. Enter `x-slack-zeezide://localhost/oauth-redirect` and click `Add`
5. Click `Save URLs`

After that, adding the account in Shrug should work.

**Comment by helje5** [comment]
Thanks! Maybe we should move this info to the Wiki?

**Comment by sensibleish** [comment]
For sure! When I click the Wiki tab I just get redirected back to the repository home page, so I did not see a way to add info there.

**Comment by helje5** [comment]
I tried to press the right toggle, can you try editing again? Thanks!

**Comment by sensibleish** [comment]
I can see it now. I don't see an existing page to put this info, so I can make one.

Thanks for working on Shrugs. It's fun to try.

**Comment by helje5** [comment]
Let me know if it doesn't let you create/edit a page, and I'll port it over.
