### ISSUE TITLE
Should be able to open a channel in its own window

### ISSUE THREAD

**Issue by jpinnix** [ZeeZide/Shrugs#14]
The app should be able to open a channel in its own window, without the Channels/DMs sidebar or the accounts sidebar visible.

**Comment by helje5** [comment]
Yes, that probably makes sense (similar to threads). I was wondering whether those windows should be full main windows just with the sidebars collapsed.

**Comment by jpinnix** [comment]
Yes, if you leave them as full windows with collapsed sidebars, then if you need to quickly jump into another channel you could just expand the sidebar.

Cultured Code’s Things works like this. You can open as many main windows as you want, but you can also collapse or open sidebars on any of them.

**Comment by helje5** [comment]
I need to check how I implement the new macOS 11 window setups, maybe I can tackle this as part of the effort.
