### ISSUE TITLE
Title doesn't keep sync with the current channel/workspace when navigating with the forward/back button

### ISSUE THREAD

**Issue by goranmoomin** [ZeeZide/Shrugs#24]
As the issue title mentions, the title of the window doesn't keep in sync with the current channel and workspace. (Sorry for the video watermark.)

https://user-images.githubusercontent.com/37990858/107961807-ba624e80-6fe9-11eb-84ec-bb9678449bfe.mp4

**Comment by helje5** [comment]
Thanks for reporting! Should be fixed and available in the next release.

**Comment by helje5** [comment]
(there is a another minor issue that the very first history item doesn't carry the channel, just the workspace).

**Comment by goranmoomin** [comment]
Hmm, I guess that can only be checked after the fix has shipped, but just checking the history button doesn't show that problem to me... (BTW I would very appreciate if the history menu popped up on a long click on the forward/back button like Safari/Finder, etc.)
<img width="915" alt="스크린샷 2021-02-17 오후 12 03 30" src="https://user-images.githubusercontent.com/37990858/108150540-280c9880-7118-11eb-8af1-dc44b9f63e1c.png">

**Comment by helje5** [comment]
Yes, the bug only affects the window title. In v1.2.0 the window title is not updated if the target location is in the navigation history already, that's the bug which I fixed.

Note sure whether the long-press menu in Safari is a custom control, I think so. Though maybe it is the [menuFormRepresentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Tasks/SettingTBItemRep.html#//apple_ref/doc/uid/20000722) thing, I could try that.
