### ISSUE TITLE
Purchase sheet buttons gets clipped in Big Sur

### ISSUE THREAD

**Issue by goranmoomin** [ZeeZide/Shrugs#25]
The shadows of the buttons on the purchase sheet in the store tab of the preferences window are clipped in Big Sur in light mode. (I guess it also happens in dark mode, but it isn't as prominent as in light mode.)

<img width="978" alt="Shrugs Clipped Buttons Bug" src="https://user-images.githubusercontent.com/37990858/107962426-48d6d000-6fea-11eb-9ec7-935dad6da499.png">

**Comment by helje5** [comment]
Same issue in the "enter license" panel (+ button in the lower-left). Fixed, will arrive in the next update, thanks for reporting!
