### ISSUE TITLE
Allow Look up in the reply popover

### ISSUE THREAD

**Issue by goranmoomin** [ZeeZide/Shrugs#27]
This is a half feature-request, half bug I guess?

I expected the look up feature (I usually bring it up with force touch, but also with right click) work on not only the detached reply window, but also in the popover. I've attached a video that shows that Look up works in the detached window, but not in the popover. 

https://user-images.githubusercontent.com/37990858/107966284-f8ae3c80-6fee-11eb-8753-5578a22e04b7.mp4

**Comment by helje5** [comment]
I don't think I actually do anything special to support lookup, it's automatic for NSTextField's. But I can confirm, it doesn't work for me either (I usually right-click, and the lookup is missing from the context menu).

I suspect that this is just the default macOS behaviour, e.g. I can't trigger it in a Calendar.app event popup either. Maybe they want to avoid nested popovers?

**Comment by goranmoomin** [comment]
Ok, I guess then this is intended behavior in macOS! Thanks for taking time on looking into it :-)
