### ISSUE TITLE
"Use Zeezide ID" button in Accounts prefs: "We're very sorry, but your browser is not supported."

### ISSUE THREAD

**Issue by dreness** [ZeeZide/Shrugs#34]
Although I'm not sure what this button *should* do, I'm fairly sure it's not this. This seems like it breaks the ability to configure new accounts with ZeeZide IDs, leaving me to ponder the difference between "sorry" and "very sorry" :)

I ran it through an SSL proxy to obtain a cleartext traffic capture, which I can supply privately if needed.

![image](https://user-images.githubusercontent.com/5242016/136670878-258685b2-53a1-4985-aea6-e905fdb59fc1.png)

**Comment by helje5** [comment]
It should bring up the authentication page for Slack. I'll check what might be different and whether I can repro.

Thanks for reporting!

**Comment by owenversteeg** [comment]
Also got the same issue - OSX Monterey 12.0.1 (21A559) on a M1 Air. Let me know if there's any diagnostics you'd like :)

**Comment by helje5** [comment]
I probably just need to adjust the user agent, it is on the list of things I need to do.

**Comment by hrishisd** [comment]
Is there an alternative way to set up a new account with Shrugs in the interm?

**Comment by helje5** [comment]
I try to get to it soon. But yes, there are the other options in the "Other Authentication" tab. ZZ ID auth is not the best way to run the client anyways, what would be more important is support for XOXC token auth (i.e. fix the WebAuth for the new stuff). Not sure when I get to that, it is quite a bit of work.

P.S.: If you accidentally bought it before trying it, let me know and I try to issue a refund!

**Comment by helje5** [comment]
OK, I got it working again. Need to find the time to do some testing and release a version this week.

**Comment by helje5** [comment]
Should be fixed in Marzipan 1.3 v74 (the beta version): https://zeezide.com/en/products/marzipan/archives/Marzipan.app-1.3-v74.zip

If no issues crop up, I'll release a regular Shrugs later this week.

**Comment by dreness** [comment]
Works!
