### ISSUE TITLE
Link "Report a Bug..." to this repo

### ISSUE THREAD

**Issue by DivineDominion** [ZeeZide/Shrugs#40]
When I select _Shrugs ▶ Report a Bug..._, I'm being taken to https://github.com/ZeeZide/

Had to dig for this repo the first time. My suggestion: change the URL to https://github.com/ZeeZide/Shrugs/

Also, maybe consider moving this to "Help"? I was looking for help at least :)

**Comment by helje5** [comment]
Didn't make it for 1.2.4, but the fix is in. It was correct in Marzipan already.
