### ISSUE TITLE
Pressing Command-] when "Go Forward" is unavailable flashes the "Mark as Read" toolbar button

### ISSUE THREAD

**Issue by nriley** [ZeeZide/Shrugs#5]
The keyboard shortcut should not respond if the menu item is disabled.

However, it doesn't actually seem to trigger "Mark as Read". (Nor does clicking the button do anything in this case — seems it may get Shrugs into a weird state.)

**Comment by helje5** [comment]
Right, copy/paste bug ... The toolbar button was also bound to that shortcut, fixed.
